#!/bin/bash
  
cd /home/pi/ip 

IP=`curl http://ipecho.net/plain`
PREV=`cat current_ip`

if [ "$PREV" != "$IP" ]
then
  echo $IP > current_ip
  git add current_ip
  git commit -m "IP change on `date`"
  git push https://zfishies:zf123zf123@github.com/zfishies/public-ip.git
fi

